services:
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    volumes:
      - ./data:/usr/share/nginx/html:ro
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
